name: Pulumi Backend Lint, Test & Build

on:
  repository_dispatch:
    types: [build]

jobs:
  builds:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: run pulumi backend
        run: |
          npm run dev > /dev/null 2>&1 &
          sleep 20s
      - name: autodeploy
        run: |
          curl -X GET 'http://localhost:5000/autodeploy' -H 'accept: application/json'
